//! Pure authorize and token-exchange decisions.
//!
//! These functions take typed, already-validated inputs (P0 rules run first) and
//! injected instants/fakes; they perform no I/O. Effectful work (generating and
//! persisting the code, consuming the code, signing) is executed by the handler
//! from the returned decision data.

use chrono::{DateTime, Duration, Utc};

use better_auth_core::{
    AuthorizationCodeRecord, ClientId, ClientType, CodeChallenge, CodeChallengeMethod, Nonce,
    OAuthClient, RedirectUri, ScopeSet, State, SubjectId,
};

use super::error::OAuthError;
use super::requests::{AuthenticatedSubject, AuthorizationRequest, PromptMode, TokenRequest};
use super::rules::verify_pkce;
use super::token::{hash_client_secret, is_expired};

/// The authorize decision per the v1 prompt/consent matrix.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AuthorizeDecision {
    /// Issue an authorization code. The handler generates the code value, persists
    /// it, and redirects to `redirect_uri` with `code` and `state`.
    IssueCode(AuthorizationGrant),
    /// Delegate to the host login UI; the user re-enters authorize after login.
    RequireLogin,
    /// Return an error via the (already validated) redirect URI, echoing `state`.
    Deny {
        error: OAuthError,
        redirect_uri: RedirectUri,
        state: Option<State>,
    },
}

/// Parameters for an authorization code to be issued. The opaque code value is
/// generated by the handler from `SecureRandom`, not here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthorizationGrant {
    pub client_id: ClientId,
    pub subject: SubjectId,
    pub redirect_uri: RedirectUri,
    pub scope: ScopeSet,
    pub code_challenge: CodeChallenge,
    pub code_challenge_method: CodeChallengeMethod,
    pub nonce: Option<Nonce>,
    pub state: Option<State>,
    pub auth_time: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

/// Decides the authorize outcome from the session state, prompt, and host hook
/// availability. `code_ttl` and `now` set the code's expiry.
pub fn decide_authorization(
    request: &AuthorizationRequest,
    subject: Option<&AuthenticatedSubject>,
    has_login_hook: bool,
    now: DateTime<Utc>,
    code_ttl: Duration,
) -> AuthorizeDecision {
    match (subject, request.prompt) {
        (Some(sub), PromptMode::Default | PromptMode::None) => {
            AuthorizeDecision::IssueCode(AuthorizationGrant {
                client_id: request.client_id.clone(),
                subject: sub.subject.clone(),
                redirect_uri: request.redirect_uri.clone(),
                scope: request.scope.clone(),
                code_challenge: request.code_challenge.clone(),
                code_challenge_method: request.code_challenge_method,
                nonce: request.nonce.clone(),
                state: request.state.clone(),
                auth_time: sub.auth_time,
                expires_at: now + code_ttl,
            })
        }
        (Some(_), PromptMode::Login) | (None, PromptMode::Default | PromptMode::Login) => {
            if has_login_hook {
                AuthorizeDecision::RequireLogin
            } else {
                deny_login_required(request)
            }
        }
        (None, PromptMode::None) => deny_login_required(request),
    }
}

/// Builds a `login_required` denial returned via the validated redirect URI.
fn deny_login_required(request: &AuthorizationRequest) -> AuthorizeDecision {
    AuthorizeDecision::Deny {
        error: OAuthError::login_required("authentication is required"),
        redirect_uri: request.redirect_uri.clone(),
        state: request.state.clone(),
    }
}

/// A validated token grant ready for id_token + access-token issuance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TokenGrant {
    pub client_id: ClientId,
    pub subject: SubjectId,
    pub scope: ScopeSet,
    pub nonce: Option<Nonce>,
    pub auth_time: DateTime<Utc>,
}

/// Authenticates the client at the token endpoint (failure order step 1).
///
/// Confidential clients must present a secret that hashes to the stored hash;
/// public clients must present no secret (they are authenticated by PKCE at a
/// later step). A bad/missing confidential secret, or a secret on a public
/// client, is `invalid_client`.
pub fn authenticate_client(
    client: &OAuthClient,
    provided_secret: Option<&str>,
) -> Result<(), OAuthError> {
    match client.client_type {
        ClientType::Confidential => {
            let secret = provided_secret
                .ok_or_else(|| OAuthError::invalid_client("client secret is required"))?;
            let stored = client.secret_hash.as_deref().ok_or_else(|| {
                OAuthError::invalid_client("confidential client has no registered secret")
            })?;
            // Secrets are high-entropy; comparing their SHA-256 hashes is sufficient.
            if hash_client_secret(secret) == stored {
                Ok(())
            } else {
                Err(OAuthError::invalid_client("invalid client secret"))
            }
        }
        ClientType::Public => {
            if provided_secret.is_some() {
                Err(OAuthError::invalid_client(
                    "public client must not present a client secret",
                ))
            } else {
                Ok(())
            }
        }
    }
}

/// Validates the consumed authorization code against the token request
/// (failure order steps 2-4): missing code -> redirect match -> PKCE/expiry.
///
/// `consumed` is the result of the atomic consume the handler performed after
/// client authentication; `None` means the code was absent/expired -> `invalid_grant`.
pub fn decide_token_grant(
    request: &TokenRequest,
    client: &OAuthClient,
    consumed: Option<&AuthorizationCodeRecord>,
    now: DateTime<Utc>,
) -> Result<TokenGrant, OAuthError> {
    // step 2: the code must have been consumed (present and unexpired).
    let record =
        consumed.ok_or_else(|| OAuthError::invalid_grant("authorization code is invalid or used"))?;
    if is_expired(now, record.expires_at) {
        return Err(OAuthError::invalid_grant("authorization code has expired"));
    }
    if record.client_id != client.client_id {
        return Err(OAuthError::invalid_grant(
            "authorization code was issued to a different client",
        ));
    }
    // step 3: redirect URI exact match against the one bound at authorize time.
    if record.redirect_uri != request.redirect_uri {
        return Err(OAuthError::invalid_grant(
            "redirect_uri does not match the authorization request",
        ));
    }
    // step 4: PKCE verification.
    let verifier = request
        .code_verifier
        .as_ref()
        .ok_or_else(|| OAuthError::invalid_grant("code_verifier is required"))?;
    verify_pkce(&record.code_challenge, record.code_challenge_method, verifier)?;
    Ok(TokenGrant {
        client_id: record.client_id.clone(),
        subject: record.subject.clone(),
        scope: record.scope.clone(),
        nonce: record.nonce.clone(),
        auth_time: record.auth_time,
    })
}
