[package]
name = "better-auth-api"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Plugin implementations for better-auth"
repository = { workspace = true }

[dependencies]
better-auth-core = { workspace = true, default-features = false, features = ["derive"] }

# Asynchronous runtime
async-trait = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Validation
validator = { workspace = true }

# Time handling
chrono = { workspace = true }

# Cookie handling
cookie = { workspace = true }

# Data structures
uuid = { workspace = true, optional = true, features = ["v4"] }

# Crypto
sha2 = { workspace = true }
aes-gcm = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
rand = { workspace = true, optional = true }
base64 = { workspace = true }
totp-rs = { workspace = true, optional = true }

# Logging
tracing = { workspace = true }

# HTTP client
reqwest = { workspace = true, optional = true }

# URL
url = { workspace = true }
urlencoding = "2"
bon = "3.3"
governor = { version = "0.10.4", optional = true }
nonzero_ext = { version = "0.3.0", optional = true }
axum = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = ["native-tls"]
local-futures = ["better-auth-core/local-futures"]
admin = []
api-key = ["dep:governor", "dep:nonzero_ext", "dep:rand"]
device-authorization = ["dep:rand"]
email-verification = ["dep:uuid"]
native-plugins = [
    "admin",
    "api-key",
    "device-authorization",
    "email-verification",
    "organization",
    "passkey",
    "password-management",
    "two-factor",
    "user-management",
]
oauth-native-http = ["dep:reqwest"]
native-crypto = ["dep:rand"]
organization = []
passkey = ["dep:rand"]
password-management = ["dep:uuid"]
two-factor = ["dep:rand", "dep:totp-rs"]
user-management = ["dep:uuid"]
native-tls = [
    "native-plugins",
    "native-crypto",
    "oauth-native-http",
    "reqwest/default-tls",
    "better-auth-core/jwt",
    "better-auth-core/password-argon2",
    "better-auth-core/native-id",
]
rustls = [
    "native-plugins",
    "native-crypto",
    "oauth-native-http",
    "reqwest/rustls-tls",
    "better-auth-core/jwt",
    "better-auth-core/password-argon2",
    "better-auth-core/native-id",
]
axum = ["dep:axum", "better-auth-core/axum"]
