use std::collections::HashMap;

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::{AuthError, AuthResult};
use crate::threading::RuntimeSendSync;
use crate::types::HttpMethod;

/// Semantic ID family requested from an [`IdGenerator`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IdKind {
    User,
    Session,
    Account,
    Verification,
    Organization,
    Member,
    Invitation,
    TwoFactor,
    ApiKey,
    Passkey,
    OAuthState,
}

#[cfg(not(feature = "local-futures"))]
pub type SharedClock = std::sync::Arc<DynClock>;
#[cfg(feature = "local-futures")]
pub type SharedClock = std::rc::Rc<DynClock>;

#[cfg(not(feature = "local-futures"))]
pub type SharedSecureRandom = std::sync::Arc<DynSecureRandom>;
#[cfg(feature = "local-futures")]
pub type SharedSecureRandom = std::rc::Rc<DynSecureRandom>;

#[cfg(not(feature = "local-futures"))]
pub type SharedIdGenerator = std::sync::Arc<DynIdGenerator>;
#[cfg(feature = "local-futures")]
pub type SharedIdGenerator = std::rc::Rc<DynIdGenerator>;

#[cfg(not(feature = "local-futures"))]
pub type SharedSessionTokenGenerator = std::sync::Arc<DynSessionTokenGenerator>;
#[cfg(feature = "local-futures")]
pub type SharedSessionTokenGenerator = std::rc::Rc<DynSessionTokenGenerator>;

#[cfg(not(feature = "local-futures"))]
pub type SharedOAuthHttpClient = std::sync::Arc<DynOAuthHttpClient>;
#[cfg(feature = "local-futures")]
pub type SharedOAuthHttpClient = std::rc::Rc<DynOAuthHttpClient>;

#[cfg(not(feature = "local-futures"))]
pub type SharedJwtSigner = std::sync::Arc<DynJwtSigner>;
#[cfg(feature = "local-futures")]
pub type SharedJwtSigner = std::rc::Rc<DynJwtSigner>;

#[cfg(not(feature = "local-futures"))]
pub type SharedJwksProvider = std::sync::Arc<DynJwksProvider>;
#[cfg(feature = "local-futures")]
pub type SharedJwksProvider = std::rc::Rc<DynJwksProvider>;

/// Supplies the current time for portable auth decisions.
pub trait Clock: RuntimeSendSync + 'static {
    /// Returns the current UTC time.
    ///
    /// Preconditions:
    /// - The caller is executing an auth decision that needs wall-clock time.
    ///
    /// Effects:
    /// 1. Reads time from the configured runtime clock.
    ///
    /// Does not:
    /// - Persist data.
    /// - Generate random bytes or IDs.
    ///
    /// Idempotency:
    /// - Not idempotent; repeated calls may return different instants.
    fn now(&self) -> DateTime<Utc>;
}

/// Supplies cryptographically secure random bytes.
pub trait SecureRandom: RuntimeSendSync + 'static {
    /// Fills `dest` with cryptographically secure random bytes.
    ///
    /// Preconditions:
    /// - `dest` is the exact output buffer the caller intends to use.
    ///
    /// Effects:
    /// 1. Reads entropy from the configured runtime source.
    /// 2. Mutates `dest` in place.
    ///
    /// Does not:
    /// - Format tokens.
    /// - Persist generated bytes.
    ///
    /// Idempotency:
    /// - Not idempotent; repeated calls produce different bytes.
    fn fill_bytes(&self, dest: &mut [u8]) -> AuthResult<()>;
}

/// Generates framework record IDs.
pub trait IdGenerator: RuntimeSendSync + 'static {
    /// Generates an ID for `kind`.
    ///
    /// Preconditions:
    /// - The caller has selected the semantic ID kind.
    ///
    /// Effects:
    /// 1. May read entropy or runtime-specific unique ID state.
    ///
    /// Does not:
    /// - Persist the generated ID.
    /// - Decide whether caller-supplied IDs are allowed.
    ///
    /// Idempotency:
    /// - Not idempotent; repeated calls should produce distinct IDs.
    fn generate_id(&self, kind: IdKind) -> AuthResult<String>;
}

/// Generates session tokens from the configured entropy and formatting policy.
pub trait SessionTokenGenerator: RuntimeSendSync + 'static {
    /// Generates a new session token.
    ///
    /// Preconditions:
    /// - The caller is about to create a session record or equivalent auth state.
    ///
    /// Effects:
    /// 1. Reads secure entropy or runtime token source.
    /// 2. Applies the configured token formatting policy.
    ///
    /// Does not:
    /// - Persist the token.
    /// - Attach cookies.
    ///
    /// Idempotency:
    /// - Not idempotent; repeated calls should produce distinct tokens.
    fn generate_session_token(&self) -> AuthResult<String>;
}

/// HTTP request issued by an OAuth provider flow.
#[derive(Debug, Clone, PartialEq)]
pub struct OAuthHttpRequest {
    pub method: HttpMethod,
    pub url: String,
    pub headers: HashMap<String, String>,
    pub body: Vec<u8>,
}

impl OAuthHttpRequest {
    pub fn new(method: HttpMethod, url: impl Into<String>) -> Self {
        Self {
            method,
            url: url.into(),
            headers: HashMap::new(),
            body: Vec::new(),
        }
    }
}

/// HTTP response returned by an OAuth provider flow.
#[derive(Debug, Clone, PartialEq)]
pub struct OAuthHttpResponse {
    pub status: u16,
    pub headers: HashMap<String, String>,
    pub body: Vec<u8>,
}

impl OAuthHttpResponse {
    pub fn new(status: u16, body: impl Into<Vec<u8>>) -> Self {
        Self {
            status,
            headers: HashMap::new(),
            body: body.into(),
        }
    }
}

/// Sends OAuth token and userinfo HTTP requests.
#[cfg_attr(feature = "local-futures", async_trait(?Send))]
#[cfg_attr(not(feature = "local-futures"), async_trait)]
pub trait OAuthHttpClient: RuntimeSendSync + 'static {
    /// Sends one OAuth HTTP request.
    ///
    /// Preconditions:
    /// - `request` is fully formed and provider-specific validation has already run.
    ///
    /// Effects:
    /// 1. Performs one HTTP request using the configured runtime transport.
    /// 2. Returns status, headers, and body without interpreting provider JSON.
    ///
    /// Does not:
    /// - Read or write the database.
    /// - Create sessions or link accounts.
    ///
    /// Idempotency:
    /// - Depends on the provider endpoint and HTTP method; callers must not assume retries are safe.
    async fn send(&self, request: OAuthHttpRequest) -> AuthResult<OAuthHttpResponse>;
}

/// Stable key identifier (`kid`) for an OIDC signing key.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct KeyId(String);

impl KeyId {
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Signing algorithm allowlist for OIDC id_tokens.
///
/// `alg: none` is not representable; the pure core only ever asks the signer for
/// one of these algorithms.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SigningAlg {
    /// ECDSA using P-256 and SHA-256 (default).
    Es256,
    /// RSASSA-PKCS1-v1_5 using SHA-256.
    Rs256,
}

impl SigningAlg {
    /// The JOSE `alg` value.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Es256 => "ES256",
            Self::Rs256 => "RS256",
        }
    }
}

/// A single published JSON Web Key (public key material only).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kty")]
pub enum Jwk {
    /// Elliptic-curve public key (P-256 for ES256).
    #[serde(rename = "EC")]
    Ec {
        #[serde(rename = "use")]
        use_: String,
        kid: String,
        alg: String,
        crv: String,
        x: String,
        y: String,
    },
    /// RSA public key (for RS256).
    #[serde(rename = "RSA")]
    Rsa {
        #[serde(rename = "use")]
        use_: String,
        kid: String,
        alg: String,
        n: String,
        e: String,
    },
}

/// The public JSON Web Key Set published at the JWKS endpoint.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct JwkSet {
    pub keys: Vec<Jwk>,
}

/// Publishes the public JWKS used to verify issued OIDC id_tokens.
pub trait JwksProvider: RuntimeSendSync + 'static {
    /// Returns the public JWK set (public keys only, no private material).
    fn jwks(&self) -> AuthResult<JwkSet>;
}

/// Produces raw JWS signatures for OIDC id_tokens.
///
/// The pure core owns all JOSE serialization: it builds the protected header,
/// the payload, the base64url encoding, the `signing_input`, and the final
/// compact JWS. This port only signs the already-encoded `signing_input` and
/// returns raw signature bytes; it never sees claims, headers, or serialization.
#[cfg_attr(feature = "local-futures", async_trait(?Send))]
#[cfg_attr(not(feature = "local-futures"), async_trait)]
pub trait JwtSigner: RuntimeSendSync + 'static {
    /// Returns the active signing key id and algorithm for header construction.
    fn active_key(&self) -> AuthResult<(KeyId, SigningAlg)>;

    /// Signs `signing_input = base64url(header) "." base64url(payload)`.
    ///
    /// Preconditions:
    /// - `alg` is within the [`SigningAlg`] allowlist and matches `kid`.
    /// - `signing_input` is already base64url-encoded by the pure core.
    ///
    /// Effects:
    /// 1. Computes a raw signature over `signing_input` with the active key.
    ///
    /// Does not:
    /// - Build headers or claims.
    /// - Assemble the compact JWS or base64url-encode the signature.
    ///
    /// Returns:
    /// - ES256: JOSE `r || s`. RS256: PKCS#1 v1.5 signature bytes.
    async fn sign(
        &self,
        kid: &KeyId,
        alg: SigningAlg,
        signing_input: &[u8],
    ) -> AuthResult<Vec<u8>>;
}

/// Runtime capabilities required by portable auth flows.
///
/// The generic shape keeps Worker adapters free to store local `!Send` values.
/// Native callers can use the `NativeDyn*` aliases when their runtime requires
/// `Send + Sync` trait objects.
#[derive(Debug, Clone)]
pub struct RuntimeCapabilities<C, R, I, T, O> {
    pub clock: C,
    pub secure_random: R,
    pub id_generator: I,
    pub session_tokens: T,
    pub oauth_http: O,
}

impl<C, R, I, T, O> RuntimeCapabilities<C, R, I, T, O> {
    pub fn new(
        clock: C,
        secure_random: R,
        id_generator: I,
        session_tokens: T,
        oauth_http: O,
    ) -> Self {
        Self {
            clock,
            secure_random,
            id_generator,
            session_tokens,
            oauth_http,
        }
    }
}

pub type DynClock = dyn Clock;
pub type DynSecureRandom = dyn SecureRandom;
pub type DynIdGenerator = dyn IdGenerator;
pub type DynSessionTokenGenerator = dyn SessionTokenGenerator;
pub type DynOAuthHttpClient = dyn OAuthHttpClient;

pub type DynJwtSigner = dyn JwtSigner;
pub type DynJwksProvider = dyn JwksProvider;

pub type NativeDynClock = dyn Clock + Send + Sync;
pub type NativeDynSecureRandom = dyn SecureRandom + Send + Sync;
pub type NativeDynIdGenerator = dyn IdGenerator + Send + Sync;
pub type NativeDynSessionTokenGenerator = dyn SessionTokenGenerator + Send + Sync;
pub type NativeDynOAuthHttpClient = dyn OAuthHttpClient + Send + Sync;
pub type NativeDynJwtSigner = dyn JwtSigner + Send + Sync;
pub type NativeDynJwksProvider = dyn JwksProvider + Send + Sync;

/// Shared runtime capability set used by [`crate::config::AuthConfig`].
///
/// Native builds store `Arc<dyn ...>` values whose traits retain `Send + Sync`
/// through [`RuntimeSendSync`]. `local-futures` builds store `Rc<dyn ...>` so
/// Worker-local adapters are not forced into thread-safe trait objects.
#[derive(Clone)]
pub struct AuthRuntimeCapabilities {
    pub clock: SharedClock,
    pub secure_random: SharedSecureRandom,
    pub id_generator: SharedIdGenerator,
    pub session_tokens: SharedSessionTokenGenerator,
    pub oauth_http: SharedOAuthHttpClient,
    /// OIDC id_token signer. Defaults to an [`UnavailableJwtSigner`] stub so
    /// non-OIDC native and Worker assemblies are not forced to inject one.
    pub jwt_signer: SharedJwtSigner,
    /// OIDC JWKS publisher. Defaults to an [`UnavailableJwksProvider`] stub.
    pub jwks_provider: SharedJwksProvider,
}

impl AuthRuntimeCapabilities {
    pub fn new(
        clock: SharedClock,
        secure_random: SharedSecureRandom,
        id_generator: SharedIdGenerator,
        session_tokens: SharedSessionTokenGenerator,
        oauth_http: SharedOAuthHttpClient,
    ) -> Self {
        Self {
            clock,
            secure_random,
            id_generator,
            session_tokens,
            oauth_http,
            jwt_signer: unavailable_jwt_signer(),
            jwks_provider: unavailable_jwks_provider(),
        }
    }

    /// Installs an OIDC id_token signer. Only OIDC provider assemblies call this.
    #[must_use]
    pub fn with_jwt_signer(mut self, jwt_signer: SharedJwtSigner) -> Self {
        self.jwt_signer = jwt_signer;
        self
    }

    /// Installs an OIDC JWKS publisher. Only OIDC provider assemblies call this.
    #[must_use]
    pub fn with_jwks_provider(mut self, jwks_provider: SharedJwksProvider) -> Self {
        self.jwks_provider = jwks_provider;
        self
    }
}

impl Default for AuthRuntimeCapabilities {
    fn default() -> Self {
        #[cfg(not(feature = "local-futures"))]
        {
            Self::new(
                std::sync::Arc::new(SystemClock),
                std::sync::Arc::new(UnavailableSecureRandom),
                std::sync::Arc::new(NativeIdGenerator),
                std::sync::Arc::new(NativeSessionTokenGenerator),
                std::sync::Arc::new(UnavailableOAuthHttpClient),
            )
        }

        #[cfg(feature = "local-futures")]
        {
            Self::new(
                std::rc::Rc::new(SystemClock),
                std::rc::Rc::new(UnavailableSecureRandom),
                std::rc::Rc::new(NativeIdGenerator),
                std::rc::Rc::new(NativeSessionTokenGenerator),
                std::rc::Rc::new(UnavailableOAuthHttpClient),
            )
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct SystemClock;

impl Clock for SystemClock {
    fn now(&self) -> DateTime<Utc> {
        Utc::now()
    }
}

#[derive(Debug, Clone, Copy)]
pub struct UnavailableSecureRandom;

impl SecureRandom for UnavailableSecureRandom {
    fn fill_bytes(&self, _dest: &mut [u8]) -> AuthResult<()> {
        Err(AuthError::config(
            "Secure random bytes require an injected SecureRandom capability",
        ))
    }
}

#[derive(Debug, Clone, Copy)]
pub struct NativeIdGenerator;

impl IdGenerator for NativeIdGenerator {
    fn generate_id(&self, kind: IdKind) -> AuthResult<String> {
        crate::utils::id::new_required_id(&format!("{kind:?}"))
    }
}

#[derive(Debug, Clone, Copy)]
pub struct NativeSessionTokenGenerator;

impl SessionTokenGenerator for NativeSessionTokenGenerator {
    fn generate_session_token(&self) -> AuthResult<String> {
        crate::utils::id::new_session_token()
    }
}

#[derive(Debug, Clone, Copy)]
pub struct UnavailableOAuthHttpClient;

#[cfg_attr(feature = "local-futures", async_trait(?Send))]
#[cfg_attr(not(feature = "local-futures"), async_trait)]
impl OAuthHttpClient for UnavailableOAuthHttpClient {
    async fn send(&self, _request: OAuthHttpRequest) -> AuthResult<OAuthHttpResponse> {
        Err(AuthError::config(
            "OAuth HTTP requests require an injected OAuthHttpClient capability",
        ))
    }
}

/// Default [`JwtSigner`] stub used when no OIDC signer is injected.
#[derive(Debug, Clone, Copy)]
pub struct UnavailableJwtSigner;

#[cfg_attr(feature = "local-futures", async_trait(?Send))]
#[cfg_attr(not(feature = "local-futures"), async_trait)]
impl JwtSigner for UnavailableJwtSigner {
    fn active_key(&self) -> AuthResult<(KeyId, SigningAlg)> {
        Err(AuthError::config(
            "JWT signing requires an injected JwtSigner capability",
        ))
    }

    async fn sign(
        &self,
        _kid: &KeyId,
        _alg: SigningAlg,
        _signing_input: &[u8],
    ) -> AuthResult<Vec<u8>> {
        Err(AuthError::config(
            "JWT signing requires an injected JwtSigner capability",
        ))
    }
}

/// Default [`JwksProvider`] stub used when no OIDC JWKS source is injected.
#[derive(Debug, Clone, Copy)]
pub struct UnavailableJwksProvider;

impl JwksProvider for UnavailableJwksProvider {
    fn jwks(&self) -> AuthResult<JwkSet> {
        Err(AuthError::config(
            "JWKS publication requires an injected JwksProvider capability",
        ))
    }
}

#[cfg(not(feature = "local-futures"))]
fn unavailable_jwt_signer() -> SharedJwtSigner {
    std::sync::Arc::new(UnavailableJwtSigner)
}
#[cfg(feature = "local-futures")]
fn unavailable_jwt_signer() -> SharedJwtSigner {
    std::rc::Rc::new(UnavailableJwtSigner)
}

#[cfg(not(feature = "local-futures"))]
fn unavailable_jwks_provider() -> SharedJwksProvider {
    std::sync::Arc::new(UnavailableJwksProvider)
}
#[cfg(feature = "local-futures")]
fn unavailable_jwks_provider() -> SharedJwksProvider {
    std::rc::Rc::new(UnavailableJwksProvider)
}

pub type LocalRuntimeCapabilitiesDyn = RuntimeCapabilities<
    Box<DynClock>,
    Box<DynSecureRandom>,
    Box<DynIdGenerator>,
    Box<DynSessionTokenGenerator>,
    Box<DynOAuthHttpClient>,
>;

pub type NativeRuntimeCapabilitiesDyn = RuntimeCapabilities<
    Box<NativeDynClock>,
    Box<NativeDynSecureRandom>,
    Box<NativeDynIdGenerator>,
    Box<NativeDynSessionTokenGenerator>,
    Box<NativeDynOAuthHttpClient>,
>;
